name: Build iOS IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: |
          cd ios
          echo "platform :ios, '13.0'" >> Podfile  # Добавляем платформу
          pod repo update
          cd ..

      - name: Build Debug IPA (unsigned)
        run: |
          flutter build ios --debug --no-codesign
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload
  
      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-unsigned
          path: app.ipa